#!/bin/sh
#
# Update JNI method names to reflect the LTS library names

for i in native_c/intel/jni/*.c
do
    ed $i <<%%%
g/Java_org_bouncycastle_crypto_fips_AESNativeEngine/s//Java_org_bouncycastle_crypto_engines_AESNativeEngine/g
g/Java_org_bouncycastle_crypto_fips_AESNativeCBC/s//Java_org_bouncycastle_crypto_engines_AESNativeCBC/g
g/Java_org_bouncycastle_crypto_fips_AESNativeCFB/s//Java_org_bouncycastle_crypto_engines_AESNativeCFB/g
g/Java_org_bouncycastle_crypto_fips_AESNativeCTR/s//Java_org_bouncycastle_crypto_engines_AESNativeCTR/g
g/Java_org_bouncycastle_crypto_fips_AESNativeGCM/s//Java_org_bouncycastle_crypto_engines_AESNativeGCM/g
g/Java_org_bouncycastle_crypto_fips_SHA256NativeDigest/s//Java_org_bouncycastle_crypto_digests_SHA256NativeDigest/g
g/Java_org_bouncycastle_crypto_fips_NativeEntropySource/s//Java_org_bouncycastle_crypto_NativeEntropySource/g
g/Java_org_bouncycastle_crypto_fips_VarientSelector/s//Java_org_bouncycastle_crypto_VarientSelector/g
g/Java_org_bouncycastle_crypto_fips_NativeFeatures/s//Java_org_bouncycastle_crypto_NativeFeatures/g
w
q
%%%

done

